FROM node:18-alpine AS builder

ARG NEXT_PUBLIC_SERVER_DOMAIN
ARG NEXT_PUBLIC_DISCORD_LINK
ARG NEXT_PUBLIC_OSU_SERVER_LIST_LINK
ARG NEXT_PUBLIC_KOFI_LINK
ARG NEXT_PUBLIC_BOOSTY_LINK
ARG NEXT_PUBLIC_STATUS_PAGE_LINK
ARG NEXT_PUBLIC_PATCHER_PAGE_ENABLED
ARG NEXT_PUBLIC_UNOPTIMIZED_IMAGES

ENV NEXT_PUBLIC_SERVER_DOMAIN=$NEXT_PUBLIC_SERVER_DOMAIN
ENV NEXT_PUBLIC_DISCORD_LINK=$NEXT_PUBLIC_DISCORD_LINK
ENV NEXT_PUBLIC_OSU_SERVER_LIST_LINK=$NEXT_PUBLIC_OSU_SERVER_LIST_LINK
ENV NEXT_PUBLIC_KOFI_LINK=$NEXT_PUBLIC_KOFI_LINK
ENV NEXT_PUBLIC_BOOSTY_LINK=$NEXT_PUBLIC_BOOSTY_LINK
ENV NEXT_PUBLIC_STATUS_PAGE_LINK=$NEXT_PUBLIC_STATUS_PAGE_LINK
ENV NEXT_PUBLIC_PATCHER_PAGE_ENABLED=$NEXT_PUBLIC_PATCHER_PAGE_ENABLED
ENV NEXT_PUBLIC_UNOPTIMIZED_IMAGES=$NEXT_PUBLIC_UNOPTIMIZED_IMAGES

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install 

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

RUN npm install -g serve

EXPOSE 3000

CMD ["npm", "run", "start"]
