{
 "title": "Sunrise Server dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Users count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_users_count_users", "legendFormat": "__auto" },
    {
     "expr": "total_restricted_users_count_users",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Of Concurrent Game Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(total_game_sessions_count_sessions[7d])",
     "legendFormat": "Max Game Sessions per 7d"
    },
    {
     "expr": "max_over_time(total_game_sessions_count_sessions[24h])",
     "legendFormat": "Max Game Sessions per 24h"
    },
    {
     "expr": "total_game_sessions_count_sessions",
     "legendFormat": "Current Game Sessions"
    }
   ]
  },
  {
   "title": "Packets Counts",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by(packet_type) (\r\n    increase(bancho_packets_handled_total[$__range])\r\n  )\r\n)",
     "legendFormat": "{{packet_type}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(span_name) (rate(traces_spanmetrics_calls_total{service=\"Sunrise\", db_system!=\"mysql\", source=\"tempo\", cluster=\"docker-compose\", span_kind=\"SPAN_KIND_SERVER\", service_name=\"Sunrise\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Scores",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_scores_count_scores", "legendFormat": "__auto" },
    { "expr": "total_scores_standard_scores", "legendFormat": "__auto" },
    { "expr": "total_scores_taiko_scores", "legendFormat": "__auto" },
    { "expr": "total_scores_catch_scores", "legendFormat": "__auto" },
    { "expr": "total_scores_mania_scores", "legendFormat": "__auto" },
    {
     "expr": "total_scores_relax_standard_scores",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_scores_relax_taiko_scores",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_scores_relax_catch_scores",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_scores_autopilot_standard_scores",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_scores_v2_standard_scores",
     "legendFormat": "__auto"
    },
    { "expr": "total_scores_v2_taiko_scores", "legendFormat": "__auto" },
    { "expr": "total_scores_v2_catch_scores", "legendFormat": "__auto" },
    { "expr": "total_scores_v2_mania_scores", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of Multi-Matches",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(current_matches_count_matches[7d])",
     "legendFormat": "Max Multi-Matches per 7d"
    },
    {
     "expr": "max_over_time(current_matches_count_matches[24h])",
     "legendFormat": "Max Multi-Matches per 24h"
    },
    { "expr": "current_matches_count_matches", "legendFormat": "Current Multi-Matches Count" }
   ]
  },
  {
   "title": "Bancho Packets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(packet_type) (rate(bancho_packets_handled_total[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Specators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(total_spectators_count_spectators[7d])",
     "legendFormat": "Max Spectators per 7d"
    },
    {
     "expr": "max_over_time(total_spectators_count_spectators[24h])",
     "legendFormat": "Max Spectators per 24h"
    },
    {
     "expr": "total_spectators_count_spectators",
     "legendFormat": "Current Spectators Count"
    }
   ]
  },
  {
   "title": "Docker services",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  container_health_state{\r\n    container_label_com_docker_compose_project=~\"osu-sunrise-infrastructure\"\r\n  }[$__interval]\r\n)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Duration 0.99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "filters": [
      { "id": "84758092", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{nestedSetParent<0 && true } | quantile_over_time(duration, 0.99)  by (rootName)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Docker services memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\r\n  container_label_com_docker_compose_project=~\"osu-sunrise-infrastructure\"\r\n} / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Slow (>100ms) HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "filters": [
      { "id": "84758092", "operator": "=", "scope": "span" }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "  {nestedSetParent<0 && duration > 100ms} | max_over_time(duration) by (rootName)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{Application=\"Sunrise\"} |= `` \r\n| json \r\n| level != `debug` \r\n| level != `info` \r\n| label_format level=detected_level",
     "legendFormat": "{{Message}}"
    }
   ]
  },
  {
   "title": "Requests send by user session id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (session_user_id, session_is_guest) (\r\n  rate(\r\n    traces_spanmetrics_calls_total{\r\n      service=\"Sunrise\",\r\n      span_kind=\"SPAN_KIND_SERVER\",\r\n      source=\"tempo\",\r\n      service_name=\"Sunrise\",\r\n      session_user_id!=\"\",\r\n      span_name!~\"\"\r\n    }[$__rate_interval]\r\n  )\r\n) * 60",
     "legendFormat": "User Id: {{session_user_id}}, Is guest: {{session_is_guest}}"
    }
   ]
  },
  {
   "title": "Traces with Error status",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "filters": [
      {
       "id": "80c89e60",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  }
 ]
}